#
# ChestSort
# Copyright © 2021 gmasil.de
#
# This file is part of ChestSort.
#
# ChestSort is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ChestSort is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ChestSort. If not, see <https://www.gnu.org/licenses/>.
#

name: ChestSort
main: de.headshotharp.chestsort.ChestSort
version: 1.16.5-1.0
api-version: 1.16
author: HeadShotHarp
description: ChestSort Plugin for Spigot 1.16.5
commands:
  chestsort:
    description: Controls ChestSort
    usage: |
           /<command> create <central/user> <material>
           /<command> delete <central/user> [confirm]
           /<command> reset <central/user> [confirm]
           /<command> info
