name: ChestSort
main: de.headshotharp.chestsort2.ChestSort
version: 1.14.4-1.0
api-version: 1.14
author: HeadShotHarp
description: ChestSort Plugin for Spigot 1.14.4
commands:
  chestsort:
    description: Controls ChestSort
    usage: |
           Usage: /<command> create <material>
           Usage: /<command> info
