name: ChestSort
main: de.headshotharp.chestsort.ChestSort
version: 1.14.4-1.0
api-version: 1.14
author: HeadShotHarp
description: >
             ChestSort Plugin for Spigot 1.14.4
commands:
  ChestSort:
    description: Shows information about ChestSort
    usage: /ChestSort